hl.curve("quick", { type = "bezier", points = { {0.15, 0}, {0.1, 1} } })
hl.animation({ leaf = "windows",     enabled = true, speed = 1.75, bezier = "quick" })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 2.7,  bezier = "quick", style = "popin 95%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 1.75, bezier = "quick" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 0.75, bezier = "quick", style = "slide" })